name: Process Flow Diagram
on:
  push:

jobs:
  project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/process/signup
        with:
          mail-address: "test@test.jp"
          password: "passw0rd"
                
